### ISSUE TITLE
Textarea Placeholder Text - Does not wrap in Safari/older Webkit 

### ISSUE THREAD

**Issue by rallison** [aFarkas/webshim#128]
This applies to newer versions of Safari (up to at least 5.1.7 [7534.57.2]) and Chrome 10-14 due to a regression in webkit.

The webkit bug report: https://bugs.webkit.org/show_bug.cgi?id=51290
The webkit changeset including the fix: http://trac.webkit.org/changeset/90971
The Chrome bug report: http://code.google.com/p/chromium/issues/detail?id=76317

Now, I'm not sure how possible it would be to shim the placeholder attribute only for these broken versions of webkit, but if possible, it would be a nice addition to the library.

**Comment by jrencz** [comment]
@aFarkas It still may not show entire placeholder in certain circumstances https://bugs.webkit.org/show_bug.cgi?id=156399
