### ISSUE TITLE
Question: possible to disable just one type of form input polyfill?

### ISSUE THREAD

**Issue by kanariezwart** [aFarkas/webshim#155]
Hello,

Don't know if this the place for questions about usage. Is it possible to disable/customize one type of polyfill?
I would like to style number element as a normal input textfield, so not to use the polyfill, but use the rest of polyfills.

Is this possible through setOptions or anything?I didn't find anything about this issue in the docs.

Futhermore, thanks for giving us a great library!

Greetz T.

**Comment by certainlyakey** [comment]
To those who will want to disable step arrows in IE with the latest version of webshim (17.04.2016) - this option, `stepArrows`, doesn't exist/work anymore.
