### ISSUE TITLE
Password placeholder positioned incorrectly

### ISSUE THREAD

**Issue by barnzilla** [aFarkas/webshim#329]
Just wondering if I can get some help with how to position this placeholder correctly?

In IE9, the password placeholder on the following page is positioned outside the password field:

http://v20140106.capl-ecsfp.ca/data-entry/

I have viewed one of the closed issues and tried using the suggested code, but it did not resolve the issue.

**Comment by drewB** [comment]
This appears to still be an issue (and fixable with the css mentioned).  was this ever fixed?
