### ISSUE TITLE
Webshim causes style issues with date/month inputs when using bootstrap

### ISSUE THREAD

**Issue by tomascassidy** [aFarkas/webshim#472]
Example: http://jsfiddle.net/9n118znw/4/

This is only visible in Firefox, as Chrome has it's own built-in picker controls.  Tested on Firefox 34.0 on Ubuntu 14.04 x64.

It looks like some of the styles are not getting copied across properly when the original input element is cloned/enhanced to create the webshims element.  I was expecting the bold labels to appear above the date/month input elements, as it does for the text/password/number input elements.

This might occur with other input types but I have only tested on date and month.

![webshim-bootstrap](https://cloud.githubusercontent.com/assets/301402/5609886/a1b04b8e-94fe-11e4-9e74-f7c1587ff413.png)

**Comment by aFarkas** [comment]
Yes and no. Has we don't have shadowdom we need to influence the styles. And I can't fix this, you can simply fix this your own by adding: 

```css
.control-label {
    display: block;
}
```

Which is also better from UX standpoint (larger label to click). See http://jsfiddle.net/9n118znw/5/

**Comment by tomascassidy** [comment]
That works great!  Thanks.
