### ISSUE TITLE
Text cursor in date input missing on Firefox with jquery versions above 1.11.0 and 2.1.0

### ISSUE THREAD

**Issue by katzenmayer** [aFarkas/webshim#475]
Don't know if this is a jquery bug or a webshim bug but when I open http://jsfiddle.net/trixta/VNuct/ in Firefox and use jQuery(edge) instead of jquery-1.11.0 and click on a date input, I can type, but I don't get a text cursor and I can not select any text.

**Comment by aFarkas** [comment]
@katzenmayer 
Thx, I think I have fixed it in the master branch. I will check later. But you can try your own.

**Comment by aFarkas** [comment]
This also should be fixed with 1.15.6-RC1.

**Comment by Campano** [comment]
Would it be possible to know what was causing the problem? I'm on webshim 1.16 & jQuery v1.12.4 and having the same problem.

**Comment by loureirorg** [comment]
Same problem. jQuery 1.12.1, webshim 1.16
