### ISSUE TITLE
yearSelect, monthSelect and daySelect broken

### ISSUE THREAD

**Issue by katzenmayer** [aFarkas/webshim#476]
Go to http://afarkas.github.io/webshim/demos/demos/cfgs/input-date.html, check any of the options yearSelect, monthSelect and/or daySelect and try to select something: it does not work.

Picking a valid date with the datepicker works in Firefox (and makes the selects work after that).

Using the datepicker does not work in IE when daySelect is checked.

**Comment by aFarkas** [comment]
I have fixed this issue. Hope you won't find another one. Also created a new pre-release. Many thanks!
