### ISSUE TITLE
Datepicker doesn't stay open when buttonOnly is set

### ISSUE THREAD

**Issue by tomascassidy** [aFarkas/webshim#478]
Example: https://afarkas.github.io/webshim/demos/demos/cfgs/input-date.html#min=&max=&value=&list=&placeholder=&startView=0&minView=0&size=1&startValue=&useDecadeBase=0&buttonOnly=on&calculateWidth=on&popover=&popover=&popover=

Tested on Firefox 35.0, Ubuntu 14.04 x64 and Windowx 7 x64.

The example is just the default demo page with buttonOnly selected.  If I click on the calendar button, the widget popup opens as normal.  If I click anywhere else on the disabled textbox, the widget popup flashes open and then immediately closes.

**Comment by aFarkas** [comment]
Thank you very much!
