### ISSUE TITLE
scripts won't load due to CSP unsafe-eval not defined.

### ISSUE THREAD

**Issue by andrewmcarthur** [aFarkas/webshim#483]
I'm getting issues with the form validation polyfill and my Content-Security-Policy settings. The browser loads polyfiller.js fine, but won't load the polyfill scripts unless I specify 'unsafe-eval' in my CSP. It's important that I keep my CSP settings as is. Is there a way to load/use the polyfills without specifying this requirement?

**Comment by aFarkas** [comment]
jQuery is used to fetch those resources. You can use:

```js
webshim.setOptions('ajax', {
    crossDomain: true
});
```

**Comment by andrewmcarthur** [comment]
Awesome, that fixes the issue :). Thanks for the quick reply!
