### ISSUE TITLE
webshim's load time optimization - best practices?

### ISSUE THREAD

**Issue by andrewmcarthur** [aFarkas/webshim#484]
Is there a "best practices" guideline on optimizing webshim's load times? Page load times have increased by at least 5 after using webshim's forms/form-ext polyfiller (even on browsers that support a chunk of forms/form-ext functionality like chrome and firefox). I'm hoping to drop the load times back down a bit if possible.

**Comment by aFarkas** [comment]
Something you can do:

1. Seperate jquery + polyfiller.js + your polyfiller initialization code (options + polyfill call) from the rest of your JS and include this package directly in your HTML with a higher priority.
2. make sure to not call ``polyfill`` after domready, call it as soon as possible
3. inline the scripts, which are always downloaded. (you can use this grunt-task: https://github.com/aFarkas/webshim/blob/gh-pages/grunt-tasks/optimize-polyfiller.js (note you can only build from dev not from minified) or you can use this builder: http://afarkas.github.io/webshim/demos/demos/cfgs/builder.html (those tasks give you a new polyfiller.js)
4. in case you are not using JS apis but only markup apis set ``webshim.setOptions('waitReady', false);``
5. keep in mind ``onload`` event means nothing to perceived performance

**Comment by andrewmcarthur** [comment]
sorry, completely forgot to say thanks! this was very helpful :)
