### ISSUE TITLE
TYPE URL FIELD 

### ISSUE THREAD

**Issue by kishorebabuthalla** [aFarkas/webshim#486]
Hi Afarkas,

i want to change the type="url"  field should allows http & without http too. right now it allows only http.so how can i do that, so please suggest me how can i change?

Thanks for advance.

**Comment by aFarkas** [comment]
In short: you can't type="url" is defined by spec. Either you use type="text" with pattern or you write a script and add http in front of it, if this is missing.

**Comment by kishorebabuthalla** [comment]
Ok, i have given the form field as below.
<input value="" name="url"  type="text"  pattern="/^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/"  class="form-control" placeholder="your website address " tabindex="2" maxlength="254" required="" aria-invalid="true">  but it still not working, showing as "Please match the requested format." 
If  u have any exact pattern about my req, please suggest me

Thanks for advance !...

**Comment by aFarkas** [comment]
Try something like this:

```html
<input pattern="(https?:\/\/)?([\da-z.-]+).([a-z.]{2,6})([\/\w .-])\/?" />
```

**Comment by kishorebabuthalla** [comment]
Hi Afarkas,

I have checked the above pattern, but it is not working, one thing i have find in this ,whatever patterns are working in normal javascript testing , those are not working in this library ex : /(http(s)?:\\)?([\w-]+\.)+[\w-]+[.com|.in|.org]+(\[\?%&=]*)?/  , showing message like " Please match the requested format."

Copied the above pattern from http://www.aspdotnet-suresh.com/2013/09/regular-expression-to-validate-url-without-http.html.

So can u check once & suggest the exact pattern.

Thank you very much!...
