### ISSUE TITLE
IE Slowness

### ISSUE THREAD

**Issue by LRFalk01** [aFarkas/webshim#487]
We are experiencing extreme slowness in our app in IE. Chrome and FF are fine. Below is a link to an example of our issue. If you test in IE, it is super slow. We do not know what we are doing wrong.

http://jsfiddle.net/790aqejo/5/

**Comment by aFarkas** [comment]
I think this should fix your problem.

**Comment by LRFalk01** [comment]
That indeed did the trick. You saved my life.

Thanks!
