### ISSUE TITLE
Error Message:  "webshim could not add support for select2"

### ISSUE THREAD

**Issue by shefik** [aFarkas/webshim#488]
Error Message in Console:

"webshim could not add support for select2"

http://select2.github.io

**Comment by shefik** [comment]
@aFarkas Thanks for fixing this issue. It works fine. However, anytime I select an option from the menu, it outputs messages to the browser's console.log, such as the select2 object, as well as the <select> tag itself.

**Comment by ryanpcmcquen** [comment]
Any chance you would add support for select2 `3.5.4`?

**Comment by howar31** [comment]
This error shows up again for 4.0.3
