### ISSUE TITLE
Date picker: no way to disable mouse wheel.

### ISSUE THREAD

**Issue by zessx** [aFarkas/webshim#489]
Using a native HTML input date, we can disable mousewheel over it. This is mainly used to avoid users to focus the input, choose a date, scroll down to continue, and notice they've changed the date unintentionally.

Example with jQuery and jQuery-mousewheel:

    <input type="date">
    <script type="text/javascript">
    $(function() {
        $('input[type="date"]').on('mousewheel', function(event) {
            event.preventDefault();
        });
    });
    </script>

Unfortunately, webshim doesn't reproduce this behavior, or doesn't seems to provide any way to do it.

*A good way to test it is to compare Chrome/Firefox behavior*

**Comment by aFarkas** [comment]
You can disable this with the following option:

```js
webshim.setOptions("forms-ext", {
	"widgets": {
		noSpinbtn: true
	}
});
```

**Comment by zessx** [comment]
Ok, I misunderstood this option. Thanks for your quick feedback!
