### ISSUE TITLE
webshim html5 form validation polyfill doesn't run w/ 0.5.5 / 0.6 webcomponents.js present

### ISSUE THREAD

**Issue by erutan** [aFarkas/webshim#497]
I've tried removing all options and just loading the forms portion of https://afarkas.github.io/webshim/demos/index.html#Forms-forms, no dice. forms-ext works (at least the date input polyfill).  I've forked a sample fiddle from webshim to show this (originally fails in a local app I'm developing). Using https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.6.0/webcomponents.min.js has the same result. No JS errors in dev console.

https://afarkas.github.io/webshim/demos/demos/forms.html#Locale-customMessages webshim functionality in question.

http://jsfiddle.net/trixta/9859C/light/ (original example)

http://jsfiddle.net/erutan/Lso7gc4c/1/ (as above with https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.5.5/webcomponents.min.js included as external dependency)

Not entirely sure whether this should be here or at webshim (I'll copy the issue in both). Here it is at the webcomponents.js repo https://github.com/webcomponents/webcomponentsjs/issues/255

**Comment by aFarkas** [comment]
This is a webcomponents issue, just run this code, with and without webcomponents:

```html
<form id="form" class="ws-validate">
	<input required=""  />
	<input type="submit" />
</form>
<script>
	$(document).on('special', function(){
		console.log('document');
	});
	$(document.body).on('special', function(){
		console.log('body');
	});
	$('form').on('special', function(){
		console.log('form');
	});
	$('input').eq(0).trigger('special');
</script>
```

**Comment by erutan** [comment]
thanks!
