### ISSUE TITLE
Supporting "minlength" in forms on Firefox

### ISSUE THREAD

**Issue by shefik** [aFarkas/webshim#499]
Firefox 36.0.4 doesn't seem to support "minlength" in forms, even though Chrome 41.0.2272.104 supports it natively. Requesting a polyfill to support it.

**Comment by aFarkas** [comment]
You can do this:

```js
webshim.bugs.bustedValidity = !('minLength' in document.createElement('input'));

webshim.polyfill('forms');
```

**Comment by shefik** [comment]
@aFarkas Thanks. It worked.
