### ISSUE TITLE
Youtube request on every page request?

### ISSUE THREAD

**Issue by Itrulia** [aFarkas/webshim#500]
Why does webshim request `https://www.youtube.com/player_api` evetho I don't use a video on the site?

**Comment by aFarkas** [comment]
I can't confirm this.

If you go to this site:
http://afarkas.github.io/webshim/demos/demos/mediaelement/responsive-mediaelement.html

You will see, that ``https://www.youtube.com/player_api`` is not loaded until you run the following code in your console:

```js
$('video').eq(0).prop('src', 'http://www.youtube.com/watch?v=H6IrUUDboZo');
```

Maybe you are using a very old version?

**Comment by Itrulia** [comment]
Thought so too but I already updated it and tried it.

    (function ($) {
        var language = $("meta[http-equiv=Content-Language]").attr('content');
    
        /****************************/
        /* HTML5 Shiv               */
        /****************************/
        if (!window.html5) {
            window.html5 = {};
        }
        window.html5.shivMethods = false;
    
        /****************************/
        /* Webshim                  */
        /****************************/
        $.webshims.setOptions('enhanceAuto',
            !(matchMedia('(max-device-width: 720px)').matches
            || matchMedia('(max-device-width: 1024px)').matches
            && Modernizr.touchevents)
        );
        $.webshims.setOptions({
            extendNative: true
        });
        $.webshims.activeLang(language);
        $.webshims.polyfill();
    })(jQuery);

is how we call it. When I isolate it so that only webshim/modernizr/jquery are running it still requires the API. The HTML does not inlcude `<video>` or flash or an youtube link.

**Comment by Itrulia** [comment]
Yeah newest version fixed it. A coworker downloaded it 2 weeks before (dunno which version) and saw the behaviour today. He forgot to rerun the Javascript build when he tried it with the newest version.

Thanks.

'trulia
