### ISSUE TITLE
Failed to load resource...412 (Precondition Failed)

### ISSUE THREAD

**Issue by shefik** [aFarkas/webshim#503]
In console in Safari is throwing the following error:

```
Failed to load resource...412 (Precondition Failed)
```

When an app is loading webshim in a subdirectory.

As a workaround, the error does not occur when the following is set:

```
$.webshims.setOptions('debug', true);
```

It seems that "debug" is required, and it must be set to TRUE to avoid having the error display in the console.

Refs. https://github.com/zikula/core/pull/2402

**Comment by aFarkas** [comment]
@shefik 

Could you try the following things:

```js
webshims.setOptions('ajax', {
	method: 'GET'
});
```

If above does not work, try the following option:

```js
webshims.setOptions('ajax', {
	crossDomain: true
});
```

Could you also check whether the file is loaded via *POST* (in case of an error) and if yes, why? Is there a global ajaxSetup setting ajax request to POST or is there something with the server?

**Comment by cmfcmf** [comment]
Oh yes, here it is: https://github.com/zikula/core/blob/1.4/src/javascript/jquery_config.js#L24
So setting the ajax method to 'GET' should fix it, could one of you please test? @shefik @craigh

**Comment by craigh** [comment]
@cmfcmf - yes this appears to fix the problem for me. :+1: 

it is odd though that the problem only exists when working from a subdirectory (e.g. http://example.com/this/doesnt/work/) but works properly in webroot (e.g. http://thisworksok.com/)

**Comment by craigh** [comment]
sorry - this was the fix that worked
```js
webshims.setOptions('ajax', {
    method: 'GET'
});
```

I didn't try the other option

**Comment by shefik** [comment]
Confirmed. This fix works for me:

```
$.webshims.setOptions('ajax', {
        method: 'GET'
});
```
