### ISSUE TITLE
form validation for email accepts user@domain without a TLD on the end

### ISSUE THREAD

**Issue by GaltMidas** [aFarkas/webshim#514]
Seems to do this in the examples too. When a user types in foo@bar the form submits.  Where can I find the regex that tests for this?  I'd be happy to fix it so that it only accepts foo@bar.baz

**Comment by thirdender** [comment]
Technically `user@domain` is a valid email address, and `domain` is the TLD. Think about it this way… `root@localhost` should be considered a valid e-mail address.

This is valid according to the W3C Working Group spec for the [e-mail input `value` attribute](http://www.w3.org/TR/html-markup/input.email.html#input.email.attrs.value.single). The regex provided by the W3C is:

    /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/

You can test it quick in your Javascript console by running:

    /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test('user@domain')

This should return true in the console.

**Comment by thirdender** [comment]
Oh, I forgot to mention… If you need specific rules (if a client absolutely wants to require e-mail addresses have a `.com` or some other similar TLD), you should be able to add a pattern for custom validation. Found this on an [answer on SO](http://stackoverflow.com/a/20461010/379160):

    <input type="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" />

This should work with Webshims (not 100% sure), but as pointed out on [html5pattern.com](http://html5pattern.com/Emails), "Every regular expression for email validation is missing something." They recommend just using the browser validation as is.

**Comment by aFarkas** [comment]
Everything what thirdender said. Here is a better pattern to be used in conjunction type email:

```html
<input type="email" pattern=".+\.[a-zA-Z]{2,6}" />
```

**Comment by GaltMidas** [comment]
Thanks aFarkas and thirdender for the in depth help. I really appreciate it.  Great project too.
