### ISSUE TITLE
form level custom validation

### ISSUE THREAD

**Issue by wendelin** [aFarkas/webshim#520]
How do you best implement form level validation with webshim's messages?
e.g. Ensuring the files selected for upload are combined not more then X bytes.

As far as I can tell webshim.addCustomValidityRule does not work on: `form, input[type="submit"], button[type="submit"]`.
https://github.com/aFarkas/webshim/blob/gh-pages/src/shims/form-validators.js#L14

jQuery limit idea
```javascript
$("body").one("submit", 'form[data-limit-file-bytes]', function(e) {
	var $form = $(this),
		limit = $form.attr("data-limit-file-bytes");
	
	var bytes = 0;
	$form.find('input[type="file"]:not(:disabled)').each(function(){
		$.each(this.files, function(i,file) {
			bytes += file.size;
		});
	});
	
	if (bytes > limit) {
		alert("files over upload limit!");
		return false;
	}
});

// for testing
$("form")
.eq(1)
.attr("data-limit-file-bytes", 10000000)
.attr("onsubmit","return false")
.trigger("submit")
```

**Comment by aFarkas** [comment]
webshim follows the HTML5 form spec. You have basically 3 options:

* set all ``input[type="file"]`` with at least one file to invalid
* set first  ``input[type="file"]`` with at least one file to invalid
* create a hidden ``input[type="checkbox"] and toggle it's validity according to the your group constrain
