### ISSUE TITLE
The time does not get inserted properly

### ISSUE THREAD

**Issue by shefik** [aFarkas/webshim#522]
When using the form ext polyfill for the input type "datetime", the time does not get inserted properly, when the hour is 12 a.m.,

For example, clicking `Now` has this inserted in the form field:

`05/26/2015 :49`

When the expected result is:

`05/26/2015 12:49 AM`

**Comment by aFarkas** [comment]
will fix this sunday.

**Comment by shefik** [comment]
Thanks.
