### ISSUE TITLE
Trouble with hidden date fields

### ISSUE THREAD

**Issue by warren5236** [aFarkas/webshim#523]
We're having problems with hidden date fields in IE11.  We show/hide a date field depending on user input and it works perfect in browsers that support the date input type but of course IE doesn't.  :-(

If we hide the element itself we see the webshim input field and then when we click the field it shows the input.

## Before Click:
![screenshot 1432648509](https://cloud.githubusercontent.com/assets/292295/7814038/7b8cb958-038d-11e5-9bba-b241ecea178c.png)

## After Click:
![screenshot 1432648516](https://cloud.githubusercontent.com/assets/292295/7814043/7f00df9c-038d-11e5-80d8-c41b952a620a.png)

## Code:

    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="utf-8"/>
        
        <meta name="viewport" content="width=device-width" />
        
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
        <script src="/library/webshim-1.15.7/js-webshim/minified/polyfiller.js"></script>
        
        <script>
            webshims.setOptions('basePath', '/library/webshim-1.15.7/js-webshim/minified/shims/');
            webshims.polyfill('forms forms-ext');

            $(function(){
                $(document).on('click', '#clickMe', function(){
                    $('.showNow').show();
                });
            });
        </script>
        
        <style>
            .showNow{
                display:none;
            }
        </style>

        <title>Webshims and jQuery Mobile</title>
    </head>

    <body>
            <form>
                <div>
                    <input type="date" name="test" class="showNow">
                </div>

                <input type="button" id="clickMe" value="Click Me">

            </form>
    </body>
    </html>   

If we hide the parent element the webshim element doesn't get displayed correctly after it's unhidden.  I'm thinking this is the actual bug but would love some guidance.

## After Click:
![image](https://cloud.githubusercontent.com/assets/292295/7814066/aa208bd2-038d-11e5-80e6-94647034d1f1.png)

## Code:
    <!DOCTYPE html>

    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="utf-8"/>
        
        <meta name="viewport" content="width=device-width" />
        
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
        <script src="/library/webshim-1.15.7/js-webshim/minified/polyfiller.js"></script>
        
        <script>
            webshims.setOptions('basePath', '/library/webshim-1.15.7/js-webshim/minified/shims/');
            webshims.polyfill('forms forms-ext');

            $(function(){
                $(document).on('click', '#clickMe', function(){
                    $('.showNow').show();
                });
            });
        </script>
        
        <style>
            .showNow{
                display:none;
            }
        </style>

        <title>Webshims and jQuery Mobile</title>
    </head>

    <body>
            <form>
                <div class="showNow">
                    <input type="date" name="test">
                </div>

                <input type="button" id="clickMe" value="Click Me">

            </form>
    </body>
    </html>

**Comment by aFarkas** [comment]
Your problem is mainly described in this chapter:
http://afarkas.github.io/webshim/demos/index.html#Guide-dom-abstractions
Search for:
no shadowdom: .... Some styles like float or display: none/block are not reflected by the shadowdom ...

and 

re-rendering shadowelements:
...

```js
$(document).trigger('updateshadowdom');
```

Please close this issue, if this helped.
