### ISSUE TITLE
Empty bubble on fieldset in Chrome

### ISSUE THREAD

**Issue by dutchcelt** [aFarkas/webshim#531]
Grouped inputs that are required within a fieldset cause an empty bubble message to fire on submit. 
I've created an example on JSFiddle to demonstrate the behaviour on submit: http://jsfiddle.net/dutchcelt/szpwt5km/6/

Setting replaceValidationUI to false makes the problem go away.

**Comment by aFarkas** [comment]
This is fixed in master. I will do an release very soon. For more information:
https://github.com/aFarkas/webshim/issues/527

**Comment by dutchcelt** [comment]
Ah, excellent! My apologies for not spotting the other issues.

**Comment by dutchcelt** [comment]
Confirmed. Fixed in 1.15.8 release.

**Comment by aFarkas** [comment]
thx

**Comment by patil-srikanth** [comment]
Please can you tell me what needs to be done , to fix this issue .Do we need to upgrade both webshims and modernizer ? Or any other

**Comment by dutchcelt** [comment]
We've only needed to update to version 1.15.8. We have an old version of Modernizr and that doesn't effect the fix.
