### ISSUE TITLE
Code examples in the documentation miss

### ISSUE THREAD

**Issue by edge0703** [aFarkas/webshim#532]
Just wanted to implement the webshim on a form, but noticed that most of the code examples miss in the documentation: https://afarkas.github.io/webshim/demos/demos/forms.html#UI-replaceValidationUI

**Comment by aFarkas** [comment]
Yeah, it seems there was an error with the embedded examples. Just try to use without https. This should work:
http://afarkas.github.io/webshim/demos/demos/forms.html#UI-replaceValidationUI

**Comment by edge0703** [comment]
Works, thank your for the quick help!
