### ISSUE TITLE
Checkbox and radiobutton validation with "bubbles" doesn't work

### ISSUE THREAD

**Issue by edge0703** [aFarkas/webshim#533]
Checkbox and radiobutton validation with "bubbles" (not inline) only works if there is no wrapper around the input fields, like for example: 

```
<input type="radio" name="gender" value="w" id="genderw" aria-label="Geschlecht weiblich" required="required" aria-required="true" data-errormessage-value-missing="Please enter your email adress."/> <label for="genderw">weiblich</label>
<input type="radio" name="gender" value="m" id="genderm" aria-label="Geschlecht männlich" required="required" aria-required="true" data-errormessage-value-missing="Please enter your email adress."/> <label for="genderm">männlich</label>
```

But I need this layout to style evrything correctly and set up a nice structure: 
```
<fieldset class="form-rw is-radio">
	<legend class="textlabel is-radio">Geschlecht <span class="textlabel__req">*</span></legend>
		<div class="fieldgrp">
                <div class="radiobtn"><input type="radio" name="gender" value="w" id="genderw" aria-label="Geschlecht weiblich" required="required" aria-required="true" data-errormessage-value-missing="Please enter your email adress."/> <label for="genderw">weiblich</label></div>
                <div class="radiobtn"><input type="radio" name="gender" value="m" id="genderm" aria-label="Geschlecht männlich" required="required" aria-required="true" data-errormessage-value-missing="Please enter your email adress."/> <label for="genderm">männlich</label>
               </div>
        </div>
</fieldset>
```

Setting the "fieldWrapper" attribute also doesn't work. It only helps if I switch on inline validation.

**Comment by aFarkas** [comment]
This is explained on http://afarkas.github.io/webshim/demos/demos/forms.html#UI-ival search for "**Grouping multiple form fields to one validation group**". Here is a demo: https://jsfiddle.net/trixta/uMA9d/embedded/result/

Please close if this helps.

**Comment by edge0703** [comment]
I've already tried that. It only works if I switch to inline validation by setting "ws-validate" at the form. It doesn't work for "bubbles".

**Comment by aFarkas** [comment]
Can you still give me a testcase. I don't really understand what you mean. There is only one bubble visible at the time. What exactly isn't working?

Here is a fiddle to start from:
http://jsfiddle.net/trixta/Xp3Vb/light/

**Comment by edge0703** [comment]
I thought I'm crazy, but now I found out that your JSfiddle doesn't even use the webshim in Chrome, but everything that is shown is native Chrome form validation. But the thing is, even if I set up my form exactly like in the fiddle, it still shows the webshim validation and not the native Chrome validation like in your fiddle. Will try to set up a demo. Thanks for your help so far.

**Comment by edge0703** [comment]
What I also found out: The moment you remove the "ws-validation" class from the form, the "field grouping" doesn't work anymore: https://jsfiddle.net/uMA9d/63/

But I don't want this inline error messages, I want the bubbles, but with them the field grouping doesn't work.

**Comment by edge0703** [comment]
Also found another issue: If you set "replaceValidationUI: true", then radio button validation generally doesn't work anymore in Chrome. 

Generally there seems to be an issue with the fiddle:
https://jsfiddle.net/uMA9d/66/

Even when I remove "replaceValidationUI: true" and "lazyCustomMessages: true" still "replaceValidationUI" seems to applied, as I get styled error bubbles, although Safari doesn't support native HTML5 form validation.

I'm really confused now ...

**Comment by aFarkas** [comment]
Grouping error messages is a special feature of the instant validation. I actually don't know what you expect how the bubble should look like grouped?

You should also use http instead of https, because the script is linked via http and might not work in Chrome/FF and IE.

In Safari the bubbles are used to polyfill the browser, what do you expect there? Nothing?

**Comment by edge0703** [comment]
Oh, "https" was the problem. Now everything works as expected in the fiddle, thank you. Sorry for the troubles.
