### ISSUE TITLE
Recommendation for avoiding stale/cached asset files?

### ISSUE THREAD

**Issue by eddiegroves** [aFarkas/webshim#534]
I see that the script AJAX requests have cache enabled so that assets can be cached by the browser. 

I was worried that if we deploy updated versions of webshim in the future, our customers will have stale versions of the scripts/css in their browser and will not download the new files straightaway since the files are not named with version or revision strings. We version our own js/css files using gulp-rev.

Is this an actual problem in production? Any recommendations to avoid stale assets? I'd like to avoid using addCacheBuster as that would result in assets being downloaded every request.

**Comment by kraz** [comment]
You can use custom directory name. I am using token based on the application version. Something like:
```javascript
$.webshims.setOptions('basePath', '/webshim/101506/')
```
With little server side overwrite rules you can make all request to `/webshim/somedigits` to actually serve from `/webshim` directory.

**Comment by aFarkas** [comment]
I normally solve this (similar how @kraz) in the deploy step. At the time of a deploy a new timestamp is generated and every static asset (js, css, background images, fonts) are referencing these assets through this timestamp. You can see this in action here:
http://www.sos-kinderdorf.de/portal/

Here is an example asset:
http://www.sos-kinderdorf.de/blueprint/1436883923024/css/content.css

But as you can see, the number can be simply changed to any other number:
http://www.sos-kinderdorf.de/blueprint/121/css/content.css

About the ``addCacheBuster``: You should be able to use ``addCacheBuster` for your purpose`.

You can do this:

```js
webshims.setOptions('addCacheBuster', '?v='+webshim.version);
```

**Comment by eddiegroves** [comment]
Thanks @kraz and @aFarkas for the prompt and excellent responses. Both are great options - I didn't realize `addCacheBuster` had this option.
