### ISSUE TITLE
span element (ws-titlevalue) added as a string into Form validation message 

### ISSUE THREAD

**Issue by equilerex** [aFarkas/webshim#538]
![patten](https://cloud.githubusercontent.com/assets/5556216/8979460/1a645898-36aa-11e5-80bb-3bee86ede3e6.jpg)

I suspect this is a bug?

**Comment by aFarkas** [comment]
Are you using the latest version of webshim? I can't reproduce your error:
http://jsfiddle.net/trixta/4p1xq7qf/4/

Could you please provide a testcase.

**Comment by equilerex** [comment]
using the latest (1.15.8) example: http://codepen.io/anon/pen/rVQPov
