### ISSUE TITLE
Datepicker dateSign incorrect, preventing keyboard entry of a date

### ISSUE THREAD

**Issue by philayres** [aFarkas/webshim#542]
The dateSign that is set in shims/combos/5.js around line 1753 prevents dates from being entered by keyboard input.

        if(!formcfg['en-US']){
			formcfg['en-US'] = $.extend(true, {}, formcfg.en, {
				date: {firstDay: 0},
				patterns: {d: "mm/dd/yy"},
				dateSigns: '-',
			  dFormat: "/",
				meridian: ['AM', 'PM']
				
			});
		}
		if(!formcfg['en-GB']){
			formcfg['en-GB'] = $.extend(true, {}, formcfg.en, {
				date: {firstDay: 1},
				patterns: {d: "dd/mm/yy"},
				dateSigns: '-',
			  dFormat: "/",
				meridian: ['AM', 'PM']
			});
		}

For both, the dateSigns needs to be '/' not '-'

Let me know if you need more information

**Comment by jjoedouglas** [comment]
Ran into this as well.  Fiddle showing the issue: jsfiddle.net/egn9zLct/1/

**Comment by jjoedouglas** [comment]
Also in case anybody else finds this, a reasonable interim solution is listed in this SO question: http://stackoverflow.com/questions/31990004/keyboard-input-with-webshims-date-picker

**Comment by philayres** [comment]
Since duplicate chunks of code like this appear in numerous parts of the project I'm not confident enough to submit the above fix as a pull request. If an expert could confirm this is the only place the code needs to be fixed I'll happily do so, but I think I need a little more direction before I take this leap. Any feedback from a project expert?
