### ISSUE TITLE
Cloning input breaks datepicker

### ISSUE THREAD

**Issue by theahura** [aFarkas/webshim#543]
Title basically describes the issue, it looks like cloning the datepicker in jquery breaks it (in addition to display none)
See fiddle: http://jsfiddle.net/BMEc9/938/

Update: 
this seemed to kinda fix: https://github.com/aFarkas/webshim/issues/166#issuecomment-9207336
see updated fiddle above

**Comment by aFarkas** [comment]
Use `clonePolyfill` and read https://afarkas.github.io/webshim/demos/index.html#Guide-dom-abstractions

**Comment by theahura** [comment]
Brilliant, thank you.
