### ISSUE TITLE
Local not working, only Github-version

### ISSUE THREAD

**Issue by edge0703** [aFarkas/webshim#544]
Can anybody imagine why the form polyfiller only works when I integrate it from Github (https://afarkas.github.io/webshim/js-webshim/minified/polyfiller.js) but not when I download it and use the local version?

**Comment by AubreyHewes** [comment]
Locally you need the complete package. So also the shims; you can not just download and load the `polyfiller.js`

see http://afarkas.github.io/webshim/demos/index.html#Guide-installation

    <script src="js/jquery.js"></script>
    <script src="js-webshim/minified/polyfiller.js"></script>
  
    <script>
      //webshim.setOptions('basePath', '/js-webshim/minified/shims/');

      //request the features you need:
      webshim.polyfill('forms');
  
      $(function(){
        // use all implemented API-features on DOM-ready
      });
     </script>

**Comment by edge0703** [comment]
I already did that before, but with no success. But now it suddenly works - don't know what I did different now. Thanks for your help.
