### ISSUE TITLE
Date picker works, but css position of icon is wrong

### ISSUE THREAD

**Issue by ThaDafinser** [aFarkas/webshim#548]
If you use BS3 <label> then the icon position of the datepicker is wrong
Any idea if i did something wrong?

On the left one i left away the label and the position is correct. (in both FF or IE11)

![image](https://cloud.githubusercontent.com/assets/533017/10139052/81bfe940-6601-11e5-908c-7353c80e848d.png)

It seems to be the default markup of BS3 forms
![image](https://cloud.githubusercontent.com/assets/533017/10139095/aed63524-6601-11e5-8a68-8473bf6b1380.png)

**Comment by aFarkas** [comment]
You should be able to fix it with CSS. The date configurator also uses BS3 and has no problems (without doing anything).

http://afarkas.github.io/webshim/demos/demos/cfgs/input-date.html

You might also try to disable auto calculation (`calculateWidth: false`) and handle it via CSS.

**Comment by ThaDafinser** [comment]
Thank you for the feedback and sorry for the delayed answer.

It was my fault, since i added to the `input` the css class `col-md-12` which caused this behaviour
