### ISSUE TITLE
Override validity messages

### ISSUE THREAD

**Issue by tleunen** [aFarkas/webshim#556]
@aFarkas 
Hey @aFarkas, I'm trying to update webshims in an existing project to the latest version but I'm facing a few issues regarding the custom messages. They are basically not working anymore. Maybe I'm missing something.

I have setup a jsfiddle here to have a small example: http://jsfiddle.net/w2L4e5yg/1/
When hovering the textfield, the text is still the default text from the browser. In a previous version (1.8.13), it worked and we could update the text.

Could you point me in the right direction to get the same result as before?
Thanks.

**Comment by tleunen** [comment]
@aFarkas I've created an example with the old version (1.8.12) to show you it worked before: http://codepen.io/anon/pen/QjeyXJ/?editors=101
Using Firefox, I can see the custom message: 
<img width="299" alt="screen shot 2015-11-28 at 9 07 19 pm" src="https://cloud.githubusercontent.com/assets/1972567/11454990/16651e3e-9614-11e5-98cb-c343e451215b.png">

But I can't find a way to get the same result with the latest version of webshims. Could you help?

**Comment by aFarkas** [comment]
@tleunen 

The overrideMessages option is gone. It caused many many problems. I recommend, that you live with the customMessages option in combination with replaceValidationUI or the iVal. 

As an alternative you try something like this:

```js
var overrideMessage = function(){
	var changeMessage = function(){
		if(!this.title || $.data(this, 'validationTitle')){
			$.data(this, 'validationTitle', true);
			this.title = $(this).getErrorMessage();
		}
	};

	$(document).on('changedvaliditystate', function(e){
		changeMessage.call(e.target);
	});

	$('input:invalid:not([title]), select:invalid:not([title]), textarea:invalid:not([title])').each(changeMessage);
};
```

**Comment by tleunen** [comment]
I don't really want to change the default behavior of the browser so I'll go with the second alternative you suggested. Thanks a lot!

I'm closing this issue now that an alternative has been found.
