### ISSUE TITLE
Suggest some workaround - webshim Polyfill breaks due to jquery upgrade 3.6.0

### ISSUE THREAD

**Issue by rajeshkannavelu** [aFarkas/webshim#596]
Recently I have upgraded jquery to 3.6.0 for some security reason, after which the webshim was breaking. Due to which other script files are also not working.
Kindly suggest some workaround to fix the issue.

![webshim issue](https://user-images.githubusercontent.com/72302478/147834184-37cf4a6f-2870-4ebe-bc1f-ffb53e34b77a.PNG)

**Comment by PerseusTheGreat** [comment]
First line of [/readme.md](https://github.com/aFarkas/webshim/blob/gh-pages/readme.md):
**Important note: Webshim is not compatible with upcoming jQuery 3.x and I do not plan to work on a new major version. I will still fix critical bugs in the future though.**

Latest commit date/time of that file is: **Jul 22, 2015**
This means current repo has been deprecated in jQuery 2.x era, few last months before [first release of jQuery 3.x](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) on **June 9, 2016**!

I suggest you to use [jQuery Migrate Plugin](https://github.com/jquery/jquery-migrate/) as an semi-stable and non-deterministic fast solution.

Or...

I recommend you Fork this repo and adapt its codes to be compatible with jQuery 3.x based on jQuery Migrate Plugin documentations as a God-pleasing solution.

Or...

Forgot jQuery 3.x and down-grade your codes to be compatible with jQuery 2.x as a rational fast solution.

**Comment by rajeshkannavelu** [comment]
@PerseusTheGreat, Thank you for your great support, The jquery migrate plugin worked for me.
Which is the best approach between the jquery-migrate plugin and adapting its codes to be compatible with jQuery 3.x based on jQuery Migrate Plugin?

**Comment by PerseusTheGreat** [comment]
@rajeshkannavelu 
Adapting code is truly best technical solution but it will be the expensive way (more work -> more time -> more cost).

**Comment by rajeshkannavelu** [comment]
Got it, Thanks!
